### ISSUE TITLE
Issue with Ordering Pages

### ISSUE THREAD

**Issue by mesaugat** [joostvanveen/build-a-cms-with-codeigniter#4]
There is a issue with the ordering of pages. If we put Homepage as a child of About or Contact and hit the save button 'homepage' will not show up after the save.

Similarly if we put homepage and contact as a child of about. Then again the homepage doesn't show up. Take a look at the screenshot below:

![my awesome cms_2013-08-27_10-56-37](https://f.cloud.github.com/assets/4240991/1031232/b8e28d3e-0ed7-11e3-942c-f8208a708bc5.png)
The above pages show the following order, homepage is missing. Is this a problem or I am not getting the concept behind ordering the pages?

![my awesome cms_2013-08-27_10-56-23](https://f.cloud.github.com/assets/4240991/1031233/baba23ce-0ed7-11e3-9f7c-27c5b8c20452.png)

**Comment by devsantoshm** [comment]
hi the error is in the method get_nested, can you look my issue please?

**Comment by devsantoshm** [comment]
Hi Sir, you're awesome teaching in this course, but I have a problem in the file page_m.php with the method get_nested(), when i have my records in phpmyadmin of this manner

id title .... parent_id
1 homepage ... 0
5 contact ... 6
6 about ... 0

in the method get_nested(), just back array only with parent_id=0, but not the children:

Dump => array(2) {
[1] => array(6) {
["id"] => string(1) "1"
["title"] => string(8) "Homepage"
["slug"] => string(1) "/"
["order"] => string(1) "1"
["body"] => string(241) "Multiple function calls can be made if you need several joins in one query.
If you need a specific type of JOIN you can specify it via the third parameter of the function. Options are: left, right, outer, inner, left outer, and right outer."
["parent_id"] => string(1) "0"
}
[6] => array(6) {
["id"] => string(1) "6"
["title"] => string(5) "about"
["slug"] => string(5) "about"
["order"] => NULL
["body"] => string(46) "

esta página about

"
["parent_id"] => string(1) "0"
}
}
but, If I change the order of my records in phpmyadmin

id title .... parent_id
1 homepage ... 0
5 contact ... 0
6 about ... 5

I get the children

Dump => array(2) {
[1] => array(6) {
["id"] => string(1) "1"
["title"] => string(8) "Homepage"
["slug"] => string(1) "/"
["order"] => string(1) "1"
["body"] => string(241) "Multiple function calls can be made if you need several joins in one query.
If you need a specific type of JOIN you can specify it via the third parameter of the function. Options are: left, right, outer, inner, left outer, and right outer."
["parent_id"] => string(1) "0"
}
[5] => array(7) {
["id"] => string(1) "5"
["title"] => string(7) "contact"
["slug"] => string(7) "contact"
["order"] => NULL
["body"] => string(36) "

nbuevo ontenido

"
["parent_id"] => string(1) "0"
["children"] => array(6) {
["id"] => string(1) "6"
["title"] => string(5) "about"
["slug"] => string(5) "about"
["order"] => NULL
["body"] => string(46) "

esta página about

"
["parent_id"] => string(1) "5"
}
}
}

How can I resolve this problem?

Regards.

**Comment by joostvanveen** [comment]
@devsantoshm if that is the case then the records are not being ordered correctly by the SQL statement. They should be order by `parent_id, position`. This make sure all parent pages are first in the result set.

Line 75 does this:
```
$this->db->order_by($this->_order_by);
```

`$this->_order_by` is defined on line 5

**Comment by devsantoshm** [comment]
@joostvanveen ok thanks, but i have another problem with the plugin tinymce, when edit one registry, always add another paragraph p "< p >< /p >" of this manner

< p >< p >< p >< p >esta página about< /p >< /p >< /p >< /p >

when i click in button edit, add a new paragraph

< p >< p >< p >< p >< p >esta página about< /p >< /p >< /p >< /p >< /p >

how can i resolve this problem?

thanks.

**Comment by devsantoshm** [comment]
@joostvanveen ok thanks, but i have another problem with the plugin tinymce, when edit one registry, always add another paragraph p "< p >< /p >" of this manner

< p >< p >< p >< p >esta página about< /p >< /p >< /p >< /p >

when i click in button edit, add a new paragraph

< p >< p >< p >< p >< p >esta página about< /p >< /p >< /p >< /p >< /p >

how can i resolve this problem?

thanks.

**Comment by joostvanveen** [comment]
Sorry, can't help you there, @devsantoshm
